dataset:
  name: pannuke 
  train_path: ./data/fold_1.zip
  train_fold: 1
  test_path: ./data/fold_1.zip
  test_fold: 1
  img_size: 256
  batch_size: 2
  is_3d_data: False
  sample_weights: ./sampling_weights/fold_1_sample_weights.npy
  output_path: ./results
  n_classes: 6
  n_channels: 3
  weighted_sampling: False


model:
  name: adjusted_decoding
  model_type: my_model
  model_name: H2Former
  learning_rate: 0.0001
  n_epochs: 130
  window_size: 16
  determinstic: True
  seed: 2023
  res_net: ./pretrained_modules/resnet34.pth
  pretrained_vit: ./pretrained_modules/swinv2_tiny_patch4_window16_256.pth
n_workers: 2
eval_interval: 10
